//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityAppBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CityAppBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] apksigner {
            get {
                object obj = ResourceManager.GetObject("apksigner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] apktool {
            get {
                object obj = ResourceManager.GetObject("apktool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CityApp {
            get {
                object obj = ResourceManager.GetObject("CityApp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] debug {
            get {
                object obj = ResourceManager.GetObject("debug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;string name=&quot;abc_action_bar_home_description&quot;&gt;Navigate home&lt;/string&gt;
        ///    &lt;string name=&quot;abc_action_bar_up_description&quot;&gt;Navigate up&lt;/string&gt;
        ///    &lt;string name=&quot;abc_action_menu_overflow_description&quot;&gt;More options&lt;/string&gt;
        ///    &lt;string name=&quot;abc_action_mode_done&quot;&gt;Done&lt;/string&gt;
        ///    &lt;string name=&quot;abc_activity_chooser_view_see_all&quot;&gt;See all&lt;/string&gt;
        ///    &lt;string name=&quot;abc_activitychooserview_choose_application&quot;&gt;Choose an app&lt;/string&gt;
        ///    &lt;string name=&quot;abc_capital_off&quot;&gt;OFF&lt;/string&gt;
        ///    &lt;string name=&quot;abc_capital_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DEFAULT_STRING_RES {
            get {
                return ResourceManager.GetString("DEFAULT_STRING_RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;.
        /// </summary>
        internal static string DEFAULT_XML_TAGS {
            get {
                return ResourceManager.GetString("DEFAULT_XML_TAGS", resourceCulture);
            }
        }
    }
}
